### ISSUE TITLE
execute ignore files in multiple diretories

### ISSUE THREAD

**Issue by giswqs** [danielfrg/mkdocs-jupyter#129] opened 2023-03-05 02:36 UTC
Currently, `execute_ignore` only accepts a string.

```text
plugins:
  - mkdocs-jupyter:
      execute_ignore: "folder1/abc.ipynb"
```

It would be great to support a list so that we can ignore files under multiple directories, something like this:

```text
plugins:
  - mkdocs-jupyter:
      execute_ignore: ["folder1/abc.ipynb". "folder2/xyz.ipynb"]
```

**Comment by josephmcasey** [comment] 2023-03-08 19:02
Duplicate of https://github.com/danielfrg/mkdocs-jupyter/issues/119

**Comment by danielfrg** [comment] 2023-03-11 20:32
Closing as duplicate

**Closed by danielfrg** 2023-03-11 20:32 UTC
